<?php

// Error Descriptions
// HBA00000 - An unexpected error occurred during the last operation.
// HBA00001 - An unrecognized request was received.
// HBA00002 - A unique mobileId was not generated. Try again.
// HBA00003 - The specified mobileId does not exist.
// HBA00004 - The last page of the last group has been read.

// Status Descriptions
// HBA00005 - The data submitted by the mobile device was stored successfully.

	require 'dbConnect.php';
	
	define("IMAGE_URL", "http://www.happybrainapp.com/images/");
	define("PAGE_URL", "http://www.happybrainapp.com/service.php?action=view_page&pageid=");
	
	if($_SERVER['REQUEST_METHOD'] === 'POST')
	{
		if(isset($_POST['action']))
		{	
			if(isset($_POST['secret']) && $_POST['secret'] === SECRET)
			{
				if($_POST['action'] === 'add')
				{
					addDevice();
				}
				else if($_POST['action'] === 'request')
				{
					requestNextPage($_POST['mobileid']);
				}
				else if($_POST['action'] === 'post')
				{
					updateInfo($_POST['mobileid'], $_POST['comment']);
				}
				else
				{
					echo json_encode("Error: HBA00001");
				}
			}
		}
	}
	
	if(isset($_GET['action']))
	{	

		if(isset($_GET['secret']) && $_GET['secret'] === SECRET)
		{
			if($_GET['action'] === 'add')
			{
				addDevice();
			}
			else if($_GET['action'] === 'request')
			{
				requestNextPage($_GET['mobileid']);
			}
			else if($_GET['action'] === 'post')
			{
				updateInfo($_GET['mobileid'], $_GET['comment']);
			}
			else
			{
				echo json_encode("Error: HBA00001");
			}
		}
		else if($_GET['action'] === 'view_page' && isset($_GET['pageid']))
		{
			displayPage($_GET['pageid']);
		}
	}
	
	class Page
	{
		public $Title = "";
		public $Point_1 = "";
		public $Point_2 = "";
		public $Point_3 = "";
		public $Message = "";
		public $Reflect = "false";
		public $URL = "";
		public $Filename = "";
		public $PageURL = "";
		
		
		function loadPageData($pageData)
		{
			$this->Title = $pageData["Title"];
			$points = explode("|", $pageData["Points"]);
			$this->Point_1 = $points[0];
			$this->Point_2 = $points[1];
			$this->Point_3 = $points[2];
			$this->Message = $pageData["Message"];
			$this->Teaser = $pageData["Teaser"];
			$this->Reflect = ($pageData["Reflect"] == 1 ? "true" : "false");
			$this->URL = $pageData["URL"];
			$this->Filename = IMAGE_URL . $pageData["Filename"];
			$this->PageURL = PAGE_URL . $pageData["ShareID"];
		}
	}

	/**
	 * Add mobile device to system.
	 * 
	 * Returns the unique Mobile ID generated by the system or error message.
	 *     Note: Output in JSON format.
	 */
	function addDevice()
	{
		// Create a unique id (mobileId) using uniqid() function
		$mobileId = uniqid("UNF_");
		
		// Verify mobileId is not currently in the system
		if(verifyUniqueDevice($mobileId))
		{
			// Create a new entry in Devices table
			insertNewDevice($mobileId);
		}
		else
		{
			$mobileId = "Error: HBA00002";
		}
		// Return mobileId value in JSON format
		echo json_encode($mobileId);
	}
	
	/**
	 * Display the specified page.
	 * 
	 * pageId - The ShareID of the page to display.
	 */
	function displayPage($pageId)
	{
		$sharedPage = getSharedPage($pageId);
		$points = explode("|", $sharedPage["Points"]);
		
		echo "
			<html>
				<body>
					<div style='max-width: 700px; margin: auto;'>
						<h1><img style='vertical-align: middle;' src='images/happy3.png' />Happy Brain App</h1>
						
						<p>The following page has been shared with you by a Happy Brain App user.</p>
						<h3>Group: " . $sharedPage["GroupTitle"] . "</h3>
						<h3>Day " . $sharedPage["PageNum"] . ": " . $sharedPage["PageTitle"] . "</h3>
						<table>
						<tr><td>
						<figure style='float: left;'><img src='" . IMAGE_URL .$sharedPage["Filename"] . "' width='200' /></figure>
						</td><td>
						<p>" . $sharedPage["Message"] . "</p>
						<ul>";
					
					foreach($points as $point)
					{
						if(strlen($point) > 0)
						{
							echo "				<li>" . $point . "</li>";
						}
					}
					
					
		echo "		
						</ul>
						<a href='" . $sharedPage["URL"] . "' target='_blank'>Click Here to View the Study</a>
						</td></tr>
						<tr><td colspan='2'><br /><br /><a href='#' target='_blank'>Click Here to Download the HappyBrain App</a></td></tr>
						</table>
					</div>
				</body>
			</html>
		";
	}
	
	/**
	 * Get the next page in the current group or the first page of the next group.
	 * 
	 * mobileId - The unique ID generated by the system.
	 * 
	 * Returns the info for the next page or error message.
	 *     Note: Output in JSON format.
	 */
	function requestNextPage($mobileId)
	{
		// Get deviceId
		$deviceId = getDevice($mobileId);
		
		if($deviceId > 0)
		{		
			// Determine current page
			$currentPageId = getCurrentPage($deviceId);
			
			// Determine next page
			$pageId = determineNextPage($currentPageId);
			
			if($pageId > 0)
			{
				// Create a new entry in PageAssignments table
				insertNewPageAssignment($deviceId, $pageId);
				
				$page = new Page();
				$page->loadPageData(getPageInfo($pageId));
				echo json_encode((array)$page);
			}
			else
			{
				echo json_encode("Error: HBA00004");
			}
		}
		else
		{
			echo json_encode("Error: HBA00003");
		}
	}
	
	/**
	 * Accept comment from the mobile device for a specific Reflection page.
	 * 
	 * mobileId - The unique ID generated by the system.
	 * comment - The comment to store for the Reflection page.
	 * 
	 * Returns a confirmation that the page data was stored successfully or error message.
	 *     Note: Output in JSON format.
	 */
	function updateInfo($mobileId, $comment)
	{
		// Get deviceId
		$deviceId = getDevice($mobileId);
		
		if($deviceId > 0)
		{		
			// Determine current page
			$currentPageId = getCurrentPage($deviceId);
			
			// Save the comment to the current page
			$status = insertComment($deviceId, $currentPageId, $comment);
			
			if($status == 1)
			{
				echo json_encode("Status: HBA00005");
			}
			else
			{
				echo json_encode("Error: HBA00000");
			}
		}
		else
		{
			echo json_encode("Error: HBA00003");
		}
		
	}
	
	/**
	 * Change the deviceId of the specified mobile device.
	 *     Note: Primarily done when a person buys a new phone.
	 * 
	 * deviceId - A unique value obtained from the new device.
	 *            Example: The MAC address of the Wi-Fi adapter.
	 * mobileId - The unique ID generated by the system.
	 * 
	 * Returns a confirmation that the deviceId was updated successfully or error message.
	 *     Note: Output in JSON format.
	 */
	function changeDevice($deviceId, $mobileId)
	{
		// Reserved for future use
	}
?>